pipeline {
    agent { label 'Centos7_Agent' }
    parameters {
        choice(choices: 'prod', description: 'Are you sure e.g. prod', name: 'Stage')
    }
    stages {
        stage('Create Docker Image') {
            steps {
              sh 'docker build -t web-session-service .'
          }
        }
        stage('Build & Tests') {
            steps {
                sh 'docker run --rm --mount src="$(pwd)",target=/repo/,type=bind -e NODE_ENV=development -e AWS_ACCESS_KEY_ID=DummyId -e AWS_SECRET_ACCESS_KEY=DummySecretKey web-session-service ./ci/run_tests.sh'
            }
        }
        stage('Deploy Prod') {
          when {
            expression {
              currentBuild.result == null || currentBuild.result == 'SUCCESS'
            }
          }
          steps {
            sh 'docker run --rm --mount src="$(pwd)",target=/repo/,type=bind web-session-service ./deploy/deploy_prod.sh'
          }
        }
        stage('Remove Docker Image') {
            steps {
                sh 'docker rmi -f web-session-service'
            }
        }
    }
}
